import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ClerkProvider, SignedIn, SignedOut, SignInButton, UserButton } from '@clerk/nextjs'
import { auth } from "@clerk/nextjs/server";

import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>
) {
  return (
    <html lang="en">
      <ClerkProvider>
        <Script src="https://kit.fontawesome.com/603a87c223.js" strategy="afterInteractive" crossOrigin="anonymous"></Script>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header className="flex mx-auto max-w-7xl justify-between items-center p-5 border-b">
            <div className=""></div>
            <div className="flex items-center gap-8">
              <i className="fas fa-envelope text-2xl cursor-pointer text-primary"></i>
              <SignedIn>
                <div className="scale-150">
                  <UserButton />
                </div>
              </SignedIn>
            </div>
          </header>
          {children}
        </body>
      </ClerkProvider>
    </html>
  );
}
