import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ClerkProvider } from '@clerk/nextjs'
import { auth } from "@clerk/nextjs/server";
import prisma from "@/lib/prisma";
import { Toaster } from "@/components/ui/sonner"

import Script from "next/script";
import { NextResponse } from "next/server";
import Header from "@/components/Landing/Header";

import { redirect } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>
) {

  const { userId } = await auth();

  
  let user;
  if (userId) {
    user = await prisma.user.findUnique({
      where: { clerkId: userId || undefined },
    })
  }

  // if (!user) {
  //   return redirect('/register');
  // }

  let userAttendanceRequests;

  if (user) {
    if (user.role === 'ADMIN') {
      userAttendanceRequests = await prisma.attendanceRequest.findMany();
    } else if (user.role === "USER") {
      userAttendanceRequests = await prisma.attendanceRequest.findMany({
        where: { studentId: user.id }
      })
    }
  }

  return (
    <html lang="en">
      <ClerkProvider>
        <Script src="https://kit.fontawesome.com/603a87c223.js" strategy="afterInteractive" crossOrigin="anonymous"></Script>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {userAttendanceRequests && (
            <Header userAttendanceRequests={userAttendanceRequests} />
          )}
          {children}
          <Toaster />
        </body>
      </ClerkProvider>
    </html>
  );
}
